# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: RepreZen End-User Documentation
email: info@reprezen.com
baseurl: /docs
url: "http://reprezen.github.io"
asciidoctor:
  attributes:
    - icons=font
    - hardbreaks!
exclude:
- LexiconGenTemplates
- bin