pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["adding_collection_and_index_resources.htm","RepreZen API Studio Quick Start Guide � Adding Collection and Index Resources","Adding Collection and Index Resources Navigation: No topics above this level Adding Collection and Index Resources To recap, we have now defined a...",""],
["cardinality.htm","RepreZen API Studio Quick Start Guide � Cardinality","Cardinality Navigation: No topics above this level Cardinality Cardinality can be chosen from: Symbol Cardinality Omitted (\"\") zero or one ? zero ...",""],
["conclusion.htm","RepreZen API Studio Quick Start Guide � Conclusion","Conclusion Navigation: No topics above this level Conclusion This concludes the Quick Start guide. You have been introduced to the essential featu...",""],
["creating_project_and_model.htm","RepreZen API Studio Quick Start Guide � Creating a Project and RAPID Model","Creating a Project and RAPID model Navigation: No topics above this level Creating a Project and RAPID model RepreZen&#8482; API Studio organizes API an...",""],
["customising_data_type_realisat.htm","RepreZen API Studio Quick Start Guide � Customizing Data Type Realization","Customizing Data Type Realization Navigation: No topics above this level Customizing Data Type Realization This section describes basic canonical ...",""],
["customizing_referencelinks.htm","RepreZen API Studio Quick Start Guide � Customizing Reference Links","Customizing Reference Links Navigation: No topics above this level Customizing Reference Links Previously, we added two collection resource defini...",""],
["defining_data_types.htm","RepreZen API Studio Quick Start Guide � Defining Data Types","Defining Data Types Navigation: No topics above this level Defining Data Types RepreZen&#8482; API Studio uses a simple data definition language to defi...",""],
["defining_resources.htm","RepreZen API Studio Quick Start Guide � Defining Resources","Defining Resources Navigation: No topics above this level Defining Resources Now that we have some basic data types defined we can start building ...",""],
["documenting_model_elements.htm","RepreZen API Studio Quick Start Guide � Documenting Model Elements","Documenting Model Elements Navigation: No topics above this level Documenting Model Elements RepreZen API Studio includes special-purpose views fo...",""],
["generating_code_documentation.htm","RepreZen API Studio Quick Start Guide � Generating Code and Documentation","Generating Code and Documentation Navigation: No topics above this level Generating Code and Documentation Typically, you will evolve your API des...",""],
["inspecting_the_model.htm","RepreZen API Studio Quick Start Guide � Inspecting the Model","Inspecting the Model Navigation: No topics above this level Inspecting the Model We have now defined a basic RESTful API, with two completed resou...",""],
["introducing_rapid-ml.htm","RepreZen API Studio Quick Start Guide � Introducing RAPID-ML","Introducing RAPID-ML&#8482; Navigation: No topics above this level Introducing RAPID-ML&#8482; RAPID-ML&#8482;, the Modeling Language for Resource API over Data use...",""],
["introduction.htm","RepreZen API Studio Quick Start Guide � Introduction","Introduction Navigation: No topics above this level Introduction Welcome to the RAPID-ML&#8482; Quick Start Guide! Welcome! This guide will get you up t...",""],
["launching.htm","RepreZen API Studio Quick Start Guide � Launching","Launching Navigation: No topics above this level Launching RepreZen API Studio is a java-based application that is launched in various ways depend...",""],
["resolving_ambiguous_data_type_references.htm","RepreZen API Studio Quick Start Guide � Resolving Ambiguous Data Type References","Resolving Ambiguous Data Type References Navigation: No topics above this level Resolving Ambiguous Data Type References This section explains how...",""],
["sharing_and_reusing_data_models.htm","RepreZen API Studio Quick Start Guide � Sharing and Reusing Data Models","Sharing and Reusing Data Models Navigation: No topics above this level Sharing and Reusing Data Models RESTful APIs present interfaces across whic...",""],
["using_the_mock_server.htm","RepreZen API Studio Quick Start Guide � Trying the API with the Mock Service","Trying the API with the Mock Service Navigation: No topics above this level Trying the API with the Mock Service This section introduces the Repre...",""]];
